/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsVehiclesRouteImport } from './routes/settings.vehicles'
import { Route as SettingsSystemRouteImport } from './routes/settings.system'
import { Route as SettingsRegionRouteImport } from './routes/settings.region'
import { Route as SettingsHouseRouteImport } from './routes/settings.house'
import { Route as SettingsChargersRouteImport } from './routes/settings.chargers'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as OnboardingStepRouteImport } from './routes/onboarding.$step'
import { Route as HistorySessionIdRouteImport } from './routes/history.$sessionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsVehiclesRoute = SettingsVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRegionRoute = SettingsRegionRouteImport.update({
  id: '/region',
  path: '/region',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsHouseRoute = SettingsHouseRouteImport.update({
  id: '/house',
  path: '/house',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsChargersRoute = SettingsChargersRouteImport.update({
  id: '/chargers',
  path: '/chargers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => OnboardingRoute,
} as any)
const HistorySessionIdRoute = HistorySessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => HistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/chargers': typeof SettingsChargersRoute
  '/settings/house': typeof SettingsHouseRoute
  '/settings/region': typeof SettingsRegionRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/vehicles': typeof SettingsVehiclesRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/chargers': typeof SettingsChargersRoute
  '/settings/house': typeof SettingsHouseRoute
  '/settings/region': typeof SettingsRegionRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/vehicles': typeof SettingsVehiclesRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/chargers': typeof SettingsChargersRoute
  '/settings/house': typeof SettingsHouseRoute
  '/settings/region': typeof SettingsRegionRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/vehicles': typeof SettingsVehiclesRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/onboarding'
    | '/settings'
    | '/history/$sessionId'
    | '/onboarding/$step'
    | '/settings/about'
    | '/settings/chargers'
    | '/settings/house'
    | '/settings/region'
    | '/settings/system'
    | '/settings/vehicles'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/onboarding'
    | '/history/$sessionId'
    | '/onboarding/$step'
    | '/settings/about'
    | '/settings/chargers'
    | '/settings/house'
    | '/settings/region'
    | '/settings/system'
    | '/settings/vehicles'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/onboarding'
    | '/settings'
    | '/history/$sessionId'
    | '/onboarding/$step'
    | '/settings/about'
    | '/settings/chargers'
    | '/settings/house'
    | '/settings/region'
    | '/settings/system'
    | '/settings/vehicles'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/vehicles': {
      id: '/settings/vehicles'
      path: '/vehicles'
      fullPath: '/settings/vehicles'
      preLoaderRoute: typeof SettingsVehiclesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/region': {
      id: '/settings/region'
      path: '/region'
      fullPath: '/settings/region'
      preLoaderRoute: typeof SettingsRegionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/house': {
      id: '/settings/house'
      path: '/house'
      fullPath: '/settings/house'
      preLoaderRoute: typeof SettingsHouseRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/chargers': {
      id: '/settings/chargers'
      path: '/chargers'
      fullPath: '/settings/chargers'
      preLoaderRoute: typeof SettingsChargersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/history/$sessionId': {
      id: '/history/$sessionId'
      path: '/$sessionId'
      fullPath: '/history/$sessionId'
      preLoaderRoute: typeof HistorySessionIdRouteImport
      parentRoute: typeof HistoryRoute
    }
  }
}

interface HistoryRouteChildren {
  HistorySessionIdRoute: typeof HistorySessionIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistorySessionIdRoute: HistorySessionIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

interface OnboardingRouteChildren {
  OnboardingStepRoute: typeof OnboardingStepRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingStepRoute: OnboardingStepRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsChargersRoute: typeof SettingsChargersRoute
  SettingsHouseRoute: typeof SettingsHouseRoute
  SettingsRegionRoute: typeof SettingsRegionRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsVehiclesRoute: typeof SettingsVehiclesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsChargersRoute: SettingsChargersRoute,
  SettingsHouseRoute: SettingsHouseRoute,
  SettingsRegionRoute: SettingsRegionRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsVehiclesRoute: SettingsVehiclesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
